baseURL = "https://klymbdigital.com/"
disqusShortname = "klymb-digital"
googleAnalytics = "G-MHKHYFFQQF"
paginate = "3"
summaryLength = "15"
theme = "breath"
title = "A Better Website for your Business"
[markup.goldmark.renderer]
disableLanguages = "de"
unsafe = true
