# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about"
weight = 2

[[main]]
name = "Pricing"
url = "pricing"
weight = 3

[[main]]
name = "Contact"
url = "#contact"
weight = 4


# footer menu left
[[footer_left]]
name = "About us"
url = "about"

[[footer_left]]
name = "Our Work"
url = "#work"

[[footer_left]]
name = "Booking"
url = "booking"


# footer menu middle

[[footer_middle]]
name = "Pricing"
url = "pricing"

[[footer_middle]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_middle]]
name = "Terms & Conditions"
url = "terms-conditions"

